/*
 * eyecatcher.c — auto-generated by gen_eyecatcher.py
 * Do not edit by hand — regenerated each artbox build.
 */

#include "sdk/macro.h"
#include "sdk/neogeo.h"
#include <stdint.h>

#pragma GCC push_options
#pragma GCC optimize ("O0")

void NEOGEO_USER showScreen94(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen95(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen96(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen97(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen98(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen99(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen100(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);

void NEOGEO_USER showEyeCatcherMVS(void) {
    clearFix();
    clearSprs();
    showScreen94(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen95(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen96(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen97(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen98(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen99(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
    showScreen100(16, 24, 0xF, 0xAF, 16, 0x0000, 0);
    cyclexs(2);

    clearFix();
    clearSprs();
}

#pragma GCC pop_options
