/*
 * eyecatcher.c — auto-generated by gen_eyecatcher.py
 * Do not edit by hand — regenerated each artbox build.
 */

#include "sdk/macro.h"
#include "sdk/neogeo.h"
#include <stdint.h>

#define EC_SPRITE_BASE 0x0040u

#pragma GCC push_options
#pragma GCC optimize ("O0")

void NEOGEO_USER showScreen94(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen95(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen96(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen97(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen98(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen99(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen100(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);

void NEOGEO_USER showEyeCatcherMVS(void) {
    clearFix();
    clearSprs();

    showScreen94(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(80);

    showScreen94(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen95(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen96(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen97(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(35);
    showScreen98(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen99(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen100(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);

    showScreen94(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen95(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen96(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen97(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(35);
    showScreen98(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen99(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);
    showScreen100(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(50);

    showScreen100(32, 24, 0xf, 0xff, 11, 0x0000, EC_SPRITE_BASE);
    cyclexms(100);

    clearFix();
    clearSprs();
}

#pragma GCC pop_options
