/*
 * eyecatcher.c — auto-generated by gen_eyecatcher.py
 * Do not edit by hand — regenerated each artbox build.
 */

#include "sdk/macro.h"
#include "sdk/neogeo.h"
#include <stdint.h>

#pragma GCC push_options
#pragma GCC optimize ("O0")

void NEOGEO_USER showScreen94(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen95(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen96(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen97(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen98(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen99(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);
void NEOGEO_USER showScreen100(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);

void NEOGEO_USER showEyeCatcherMVS(void) {
    clearFix();
    clearSprs();

    showScreen94(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(80);

    showScreen94(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen95(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen96(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen97(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(35);
    showScreen98(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen99(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen100(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);

    showScreen94(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen95(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen96(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen97(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(35);
    showScreen98(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen99(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);
    showScreen100(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(50);

    showScreen100(54, 48, 0xb, 0x7f, 12, 0x0000, 0);
    cyclexms(100);

    clearFix();
    clearSprs();
}

#pragma GCC pop_options
