#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

PATCH_SIZE = 31
OPS = ("op1", "op2", "op3", "op4")


def parse_hex_byte(value):
    value = value.strip()
    if value.lower().startswith("0x"):
        n = int(value, 16)
    else:
        # Config uses values like C0, 1F, 08.
        n = int(value, 16)
    if not 0 <= n <= 0xFF:
        raise SystemExit(f"byte out of range: {value}")
    return n


def parse_int(value):
    value = value.strip()
    if value.lower().startswith("0x"):
        return int(value, 16)
    return int(value, 0)


def parse_op(value):
    parts = [p.strip() for p in value.split(",")]
    if len(parts) != 7:
        raise SystemExit(f"operator must have 7 values: {value}")
    return [parse_hex_byte(p) for p in parts]


def parse_config(path):
    patches = []
    current = None

    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue

        m = re.match(r"\[patch\s+(\d+)\]", line, re.I)
        if m:
            if current is not None:
                patches.append(current)
            pid = int(m.group(1))
            current = {
                "id": pid,
                "name": f"Patch {pid}",
                "alg": 0,
                "fb": 0,
                "stereo": 0xC0,
                "lfo": 0x00,
                "ops": {},
            }
            continue

        if current is None:
            raise SystemExit(f"{path}:{lineno}: data before [patch N] section")

        if "=" not in line:
            raise SystemExit(f"{path}:{lineno}: expected key=value, got: {line}")

        key, value = [x.strip() for x in line.split("=", 1)]
        key = key.lower()

        if key == "name":
            current["name"] = value
        elif key == "alg":
            current["alg"] = parse_int(value) & 0x07
        elif key == "fb":
            current["fb"] = parse_int(value) & 0x07
        elif key == "stereo":
            current["stereo"] = parse_hex_byte(value)
        elif key == "lfo":
            current["lfo"] = parse_hex_byte(value)
        elif key in OPS:
            current["ops"][key] = parse_op(value)
        else:
            raise SystemExit(f"{path}:{lineno}: unknown key: {key}")

    if current is not None:
        patches.append(current)

    patches.sort(key=lambda p: p["id"])

    if not patches:
        raise SystemExit(f"{path}: no patches found")

    for expected, patch in enumerate(patches):
        if patch["id"] != expected:
            raise SystemExit(
                f"patch IDs must be continuous. Expected {expected}, got {patch['id']}"
            )
        for op in OPS:
            if op not in patch["ops"]:
                raise SystemExit(f"patch {patch['id']} missing {op}")

    return patches


def emit_inc(patches, out):
    lines = []
    lines.append("; Generated by sound/tools/fm_patch_compile.py")
    lines.append(f".define FM_PATCH_COUNT {len(patches)}")
    lines.append(f".define FM_PATCH_SIZE {PATCH_SIZE}")
    lines.append("")
    lines.append("fm_patch_table:")

    for patch in patches:
        # YM2610 B1: feedback bits + algorithm bits
        b1 = ((patch["fb"] & 0x07) << 3) | (patch["alg"] & 0x07)
        b5 = patch["stereo"]
        lfo = patch["lfo"]

        # Patch format:
        # byte 0 = LFO register $22
        # byte 1 = B1 feedback/algorithm
        # byte 2 = B5 stereo/AMS/PMS
        # then 4 operators x 7 bytes:
        # DT/MUL, TL, AR, DR, SR, SL/RR, ENV
        data = [lfo, b1, b5]
        data.extend(patch["ops"]["op1"])
        data.extend(patch["ops"]["op2"])
        data.extend(patch["ops"]["op3"])
        data.extend(patch["ops"]["op4"])

        if len(data) != PATCH_SIZE:
            raise SystemExit(
                f"internal error: patch size {len(data)}, expected {PATCH_SIZE}"
            )

        lines.append(f"  ; patch {patch['id']} - {patch['name']}")
        row = []
        for b in data:
            row.append(f"${b:02X}")
            if len(row) == 10:
                lines.append("  .db " + ",".join(row))
                row = []
        if row:
            lines.append("  .db " + ",".join(row))
        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), newline="\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "input",
        nargs="?",
        type=Path,
        default=Path("sound/fm/patches.fm"),
    )
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("sound/driver/fm_patch_table.inc"),
    )
    args = ap.parse_args()

    patches = parse_config(args.input)
    emit_inc(patches, args.output)
    print(f"Built {args.output} ({len(patches)} patches)")


if __name__ == "__main__":
    main()
