#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

PRESET_SIZE = 6


def parse_hex_or_int(value):
    value = value.strip()
    try:
        return int(value, 0)
    except ValueError:
        return int(value, 16)


def parse_config(path):
    presets = []
    current = None

    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue

        m = re.match(r"\[preset\s+(\d+)\]", line, re.I)
        if m:
            if current is not None:
                presets.append(current)
            pid = int(m.group(1))
            current = {
                "id": pid,
                "name": f"Preset {pid}",
                "tone_mask": 0x38,
                "vol_a": 0x0A,
                "vol_b": 0x06,
                "vol_c": 0x00,
                "noise_freq": 0x00,
            }
            continue

        if current is None:
            continue

        if "=" not in line:
            raise SystemExit(f"{path}:{lineno}: expected key=value")

        key, value = [x.strip() for x in line.split("=", 1)]
        key = key.lower()

        if key == "name":
            current["name"] = value
        elif key in ("tone_mask", "vol_a", "vol_b", "vol_c", "noise_freq"):
            current[key] = parse_hex_or_int(value) & 0xFF
        elif key == "noise":
            if value.lower() in ("on", "yes", "true", "1"):
                current["tone_mask"] &= ~0x07
            else:
                current["tone_mask"] |= 0x07
        else:
            raise SystemExit(f"{path}:{lineno}: unknown key: {key}")

    if current is not None:
        presets.append(current)

    presets.sort(key=lambda p: p["id"])

    if not presets:
        presets = [{
            "id": 0,
            "name": "Default",
            "tone_mask": 0x38,
            "vol_a": 0x0A,
            "vol_b": 0x06,
            "vol_c": 0x00,
            "noise_freq": 0x00,
        }]

    for expected, preset in enumerate(presets):
        if preset["id"] != expected:
            raise SystemExit(
                f"preset IDs must be continuous. Expected {expected}, got {preset['id']}"
            )

    return presets


def emit_inc(presets, out):
    lines = [
        "; Generated by sound/tools/ssg_config_compile.py",
        f".define SSG_PRESET_COUNT {len(presets)}",
        f".define SSG_PRESET_SIZE {PRESET_SIZE}",
        "",
        "ssg_preset_table:",
    ]

    for p in presets:
        data = [
            p["tone_mask"] & 0xFF,
            p["vol_a"] & 0x0F,
            p["vol_b"] & 0x0F,
            p["vol_c"] & 0x0F,
            p["noise_freq"] & 0x1F,
            0x00,
        ]
        lines.append(f"  ; preset {p['id']} - {p['name']}")
        lines.append("  .db " + ",".join(f"${x:02X}" for x in data))

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), newline="\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", nargs="?", type=Path, default=Path("sound/ssg/config.ssg"))
    ap.add_argument("-o", "--output", type=Path, default=Path("sound/driver/ssg_config.inc"))
    args = ap.parse_args()

    presets = parse_config(args.input)
    emit_inc(presets, args.output)
    print(f"Built {args.output} ({len(presets)} presets)")


if __name__ == "__main__":
    main()
