#!/usr/bin/env python3
import argparse
from pathlib import Path

NOTE_BASE = {"c": 0, "d": 2, "e": 4, "f": 5, "g": 7, "a": 9, "b": 11}


def read_number(s, i, default):
    start = i
    while i < len(s) and s[i].isdigit():
        i += 1
    if start == i:
        return default, i
    return int(s[start:i]), i


def duration_ticks(length):
    if length <= 0:
        return 1
    return max(1, min(255, 48 // length))


def parse_mml(text):
    tempo = 120
    octave = 4
    length = 4
    volume = 12
    preset = 0
    events = []

    s = ''.join(line.split(';', 1)[0].lower() for line in text.splitlines())
    i = 0

    while i < len(s):
        c = s[i]

        if c.isspace() or c == ',':
            i += 1
            continue

        if c == 't':
            i += 1
            tempo, i = read_number(s, i, tempo)
            events.append((0xF0, tempo & 0xFF))
            continue

        if c == 'v':
            i += 1
            volume, i = read_number(s, i, volume)
            events.append((0xF1, volume & 0x0F))
            continue

        if c == 'p':
            i += 1
            preset, i = read_number(s, i, preset)
            events.append((0xF2, preset & 0x0F))
            continue

        if c == 'o':
            i += 1
            octave, i = read_number(s, i, octave)
            continue

        if c == 'l':
            i += 1
            length, i = read_number(s, i, length)
            continue

        if c == '>':
            octave += 1
            i += 1
            continue

        if c == '<':
            octave -= 1
            i += 1
            continue

        if c == '~':
            events.append((0xFE, 0x00))
            i += 1
            continue

        if c == 'r':
            i += 1
            dur, i = read_number(s, i, length)
            events.append((0x80, duration_ticks(dur)))
            continue

        if c in NOTE_BASE:
            note = NOTE_BASE[c]
            i += 1

            if i < len(s) and s[i] in ['+', '#']:
                note += 1
                i += 1
            elif i < len(s) and s[i] == '-':
                note -= 1
                i += 1

            dur, i = read_number(s, i, length)
            midi = max(0, min(127, (octave + 1) * 12 + note))
            events.append((midi, duration_ticks(dur)))
            continue

        raise SystemExit(f"unsupported SSG token {c!r} at offset {i}")

    events.append((0xFF, 0x00))
    return events


def emit_inc(tracks, out):
    lines = [
        "; Generated by sound/tools/ssg_compile.py",
        ".define SSG_TRACK_COUNT %d" % len(tracks),
        "ssg_track_table:",
    ]

    for label, _ in tracks:
        lines.append(f"  .dw {label}")

    lines.append("")

    for label, events in tracks:
        lines.append(f"{label}:")
        row = []

        for a, b in events:
            row.append(f"${a:02X},${b:02X}")
            if len(row) == 8:
                lines.append("  .db " + ",".join(row))
                row = []

        if row:
            lines.append("  .db " + ",".join(row))

        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), newline="\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("inputs", nargs="*", type=Path)
    ap.add_argument("-o", "--output", type=Path, default=Path("sound/driver/ssg_data.inc"))
    args = ap.parse_args()

    inputs = args.inputs or sorted(Path("sound/ssg").glob("*.mml"))

    tracks = []
    for idx, path in enumerate(inputs):
        tracks.append((f"ssg_track_{idx}", parse_mml(path.read_text())))

    emit_inc(tracks, args.output)
    print(f"Built {args.output} ({len(tracks)} tracks)")


if __name__ == "__main__":
    main()
