/*
 * Minimal reusable runtime example.
 * This file is intentionally original placeholder code.
 * It shows how any game can use the layer; it is not Maiya-specific.
 */

#include "ng_runtime.h"
#include "neogeo.h"
#include "macro.h"

/* Character kinds for this sample game. */
enum {
    CHAR_NONE = 0,
    CHAR_PLAYER,
    CHAR_SLIME,
    CHAR_CHEST,
    CHAR_ITEM_SEED
};

/* Actions for this sample game. */
enum {
    ACTION_PLAYER_IDLE = 1,
    ACTION_PLAYER_WALK,
    ACTION_PLAYER_ATTACK,
    ACTION_SLIME_IDLE,
    ACTION_CHEST_CLOSED,
    ACTION_CHEST_OPEN
};

/* Events for this sample game. */
enum {
    EVENT_NONE = 0,
    EVENT_ITEM_COLLECTED,
    EVENT_CHEST_OPENED,
    EVENT_LEVEL_CLEAR
};

/* Status values for this sample game. */
enum {
    STATUS_CHEST_OPENED = 1,
    STATUS_POWER_UNLOCKED
};

/* Timer values for this sample game. */
enum {
    TIMER_ATTACK_COOLDOWN = 1
};

/* Placeholder sprite tile numbers. These would be generated by spritepack later. */
#define SPR_PLAYER_IDLE_0  0x1000
#define SPR_PLAYER_IDLE_1  0x1040
#define SPR_PLAYER_WALK_0  0x1080
#define SPR_PLAYER_WALK_1  0x10c0
#define SPR_PLAYER_ATK_0   0x1100
#define SPR_PLAYER_ATK_1   0x1140
#define SPR_SLIME_IDLE_0   0x2000
#define SPR_CHEST_CLOSED   0x3000
#define SPR_CHEST_OPEN     0x3040

const NGActionCmd act_player_idle[] = {
    FRAME(SPR_PLAYER_IDLE_0, 8),
    FRAME(SPR_PLAYER_IDLE_1, 8),
    LOOP()
};

const NGActionCmd act_player_walk[] = {
    FRAME(SPR_PLAYER_WALK_0, 4),
    FRAME(SPR_PLAYER_WALK_1, 4),
    LOOP()
};

const NGActionCmd act_player_attack[] = {
    FRAME(SPR_PLAYER_ATK_0, 3),
    SFX(1),
    FRAME(SPR_PLAYER_ATK_1, 4),
    HITBOX(20, -14, 32, 18),
    WAIT(2),
    CLEAR_HITBOX(),
    GOTO(ACTION_PLAYER_IDLE)
};

const NGActionCmd act_slime_idle[] = {
    FRAME(SPR_SLIME_IDLE_0, 12),
    LOOP()
};

const NGActionCmd act_chest_closed[] = {
    FRAME(SPR_CHEST_CLOSED, 60),
    LOOP()
};

const NGActionCmd act_chest_open[] = {
    FRAME(SPR_CHEST_OPEN, 60),
    LOOP()
};

NGBorderConstraint sample_borders[] = {
    { 900, 120, 32, 80, EVENT_LEVEL_CLEAR, 2, 0, 1, 0 }
};

static void sample_sfx(uint16_t id)
{
    playSFX((uint8_t)id);
}

static void sample_events(const NGGameEvent *e)
{
    switch (e->id) {
        case EVENT_ITEM_COLLECTED:
            prop_add(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_ITEM_COUNT, 1);
            fixtext_out(2, 3, "SEED!", 1);
            break;

        case EVENT_CHEST_OPENED:
            status_set(STATUS_CHEST_OPENED);
            fixtext_out(2, 4, "CHEST OPEN", 1);
            break;

        case EVENT_LEVEL_CLEAR:
            fixtext_out(2, 5, "LEVEL CLEAR", 1);
            break;
    }
}

static void update_player(NGCharacter *c)
{
    uint16_t joy = poll_joystick();

    /* publish live player values into the Properties Matrix at time T */
    prop_set(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_X, c->x);
    prop_set(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_Y, c->y);
    prop_set(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_W, c->body_w);
    prop_set(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_H, c->body_h);
    prop_set(NG_PROP_GROUP_PLAYER, NG_PROP_PLAYER_HP, c->hp);

    if (joy & JOY_LEFT) {
        c->vx_fp = -NG_TO_FP(2);
        c->facing = 0;
        c->flip_x = 1;
        char_action(c, ACTION_PLAYER_WALK);
    } else if (joy & JOY_RIGHT) {
        c->vx_fp = NG_TO_FP(2);
        c->facing = 1;
        c->flip_x = 0;
        char_action(c, ACTION_PLAYER_WALK);
    } else {
        c->vx_fp = 0;
        char_action(c, ACTION_PLAYER_IDLE);
    }

    if ((joy & BUTTON_B) && timer_done(TIMER_ATTACK_COOLDOWN)) {
        char_action(c, ACTION_PLAYER_ATTACK);
        timer_start(TIMER_ATTACK_COOLDOWN, 20); /* 20/60 = 0.333 sec */
    }
}

static void update_chest(NGCharacter *c)
{
    NGCharacter *player = chars_find(CHAR_PLAYER);
    if (status_has(STATUS_CHEST_OPENED)) {
        char_action(c, ACTION_CHEST_OPEN);
        return;
    }

    char_action(c, ACTION_CHEST_CLOSED);

    if (player && ng_abs16((int16_t)(player->x - c->x)) < 28) {
        if (poll_joystick() & BUTTON_C) {
            char_action(c, ACTION_CHEST_OPEN);
            game_events_send(EVENT_CHEST_OPENED, 0, 0, 0);
        }
    }
}

static void collision_logic(void)
{
    NGCharacter *player = chars_find(CHAR_PLAYER);
    uint8_t i;
    if (!player || player->hit_w == 0) return;

    for (i = 0; i < NG_MAX_CHARS; i++) {
        NGCharacter *c = chars_at(i);
        if (!c || !c->active || c->kind != CHAR_SLIME) continue;
        if (ng_rect_hit(char_hit_rect(player), char_body_rect(c))) {
            char_damage(c, 1);
            c->active = 0;
        }
    }
}

void sample_runtime_start(void)
{
    NGCharacter *player;
    NGCharacter *chest;
    NGCharacter *slime;

    clearSprs();
    clearFix();

    game_runtime_init();
    actions_set_sound_hooks(sample_sfx, 0);
    game_events_set_handler(sample_events);
    game_interupt_set_hooks(0, collision_logic, 0, 0, 0);

    actions_register(ACTION_PLAYER_IDLE, act_player_idle);
    actions_register(ACTION_PLAYER_WALK, act_player_walk);
    actions_register(ACTION_PLAYER_ATTACK, act_player_attack);
    actions_register(ACTION_SLIME_IDLE, act_slime_idle);
    actions_register(ACTION_CHEST_CLOSED, act_chest_closed);
    actions_register(ACTION_CHEST_OPEN, act_chest_open);

    chars_set_game_interupt(CHAR_PLAYER, update_player);
    chars_set_game_interupt(CHAR_CHEST, update_chest);

    border_constraints_load(sample_borders, 1);

    player = chars_add(CHAR_PLAYER, 40, 160);
    char_set_sprite(player, 32, 4, 8, SPR_PLAYER_IDLE_0, NG_PAL_PLAYER_BASE);
    char_set_body(player, -8, -48, 24, 48);
    player->hp = 3;
    player->max_hp = 3;
    char_action(player, ACTION_PLAYER_IDLE);

    slime = chars_add(CHAR_SLIME, 300, 176);
    char_set_sprite(slime, 40, 2, 2, SPR_SLIME_IDLE_0, NG_PAL_ENEMY_BASE);
    char_set_body(slime, 0, -24, 24, 24);
    slime->hp = 1;
    char_action(slime, ACTION_SLIME_IDLE);

    chest = chars_add(CHAR_CHEST, 520, 176);
    char_set_sprite(chest, 44, 2, 2, SPR_CHEST_CLOSED, NG_PAL_STAGE_BASE);
    char_set_body(chest, 0, -24, 28, 24);
    char_action(chest, ACTION_CHEST_CLOSED);

    while (1) {
        waitVbl();
        game_interupt();
    }
}
