#!/usr/bin/env python3

import os
from pathlib import Path


CFG_TEXT = """# Auto-generated by artbox/gen_assets_cfg.py
# Regenerated on each make art run.

[rule:cat_backgrounds]
match_category = backgrounds
pattern = *.png
mode = screen
category = backgrounds
# Backdrops are drawn with the vertical shrink below, so the square canvas
# they are stored in covers a wide rectangle on the screen.  fit = crop
# fills that rectangle edge to edge and trims the overhang; contain would
# keep the whole picture but leave transparent bands across the backdrop.
fit = crop
anchor = center
target_width = 256
target_height = 256
display_shrink_y = 175
dither = ordered
contrast = 1.20
saturation = 1.25
sharpen_radius = 1.2
sharpen_percent = 100
sharpen_threshold = 2
kmeans_samples = 16384
kmeans_iters = 35
note = background layer or multi-level backdrop

[rule:cat_characters]
match_category = characters
pattern = *.png
mode = sprite
category = characters
fit = pad
anchor = bottom-center
target_width = 256
target_height = 256
dither = none
contrast = 1.00
saturation = 1.05
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 4096
kmeans_iters = 20
halo_strip = true
halo_luma_threshold = 220
note = 16x16 character sprite sheet

[rule:cat_effects]
match_category = effects
pattern = *.png
mode = sprite
category = effects
fit = pad
anchor = center
target_width = 256
target_height = 256
dither = none
contrast = 1.00
saturation = 1.00
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 2048
kmeans_iters = 15
halo_strip = true
halo_luma_threshold = 200
note = effects and transitions  (aggressive halo strip: bright outer ring is almost always a matte artefact on glow / spark FX)

[rule:cat_eyecatcher]
match_category = eyecatcher
pattern = *.png
mode = screen
category = eyecatcher
fit = contain
anchor = center
target_width = 256
target_height = 256
dither = ordered
contrast = 1.15
saturation = 1.20
sharpen_radius = 1.2
sharpen_percent = 120
sharpen_threshold = 2
kmeans_samples = 16384
kmeans_iters = 40
note = eyecatcher sequence

[rule:cat_particle_tiles]
match_category = npcs
pattern = zzzzzz_particle_*.png
mode = sprite
category = effect
fit = pad
anchor = bottom-left
target_width = 256
target_height = 256
dither = none
contrast = 1.05
saturation = 1.10
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 1024
kmeans_iters = 12
halo_strip = false
halo_luma_threshold = 240
note = tile-aligned 16x16 transparent particle

[rule:cat_crate_props]
match_category = npcs
pattern = zzzzzzzzzzz_crate*.png
mode = sprite
category = effect
fit = pad
anchor = bottom-left
target_width = 256
target_height = 256
dither = none
contrast = 1.05
saturation = 1.05
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 2048
kmeans_iters = 16
halo_strip = false
halo_luma_threshold = 240
note = tile-aligned collision prop

[rule:cat_big_enemy]
match_category = npcs
pattern = 020_enemy.png
mode = sprite
category = npc
# This one is a single large enemy drawn at 1238x800.  Imported onto the usual
# 256-wide canvas it needs 16 hardware sprite strips, and a formation shooter
# that puts 18 of them on screen has nowhere near that many sprites to spend.
#
# The formation spaces enemies 34 px apart across and 22 px down, so each one
# is drawn about 32x21.  Importing at exactly that size lets it be drawn at
# full scale: shrinking it in hardware from a larger canvas would resample it
# a second time, dropping columns unevenly and smearing the detail.
fit = pad
anchor = bottom-center
target_width = 32
target_height = 32
dither = none
contrast = 1.00
saturation = 1.05
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 2048
kmeans_iters = 16
halo_strip = true
halo_luma_threshold = 220
note = single large opponent, imported small enough to fit the sprite budget

[rule:cat_npcs]
match_category = npcs
pattern = *.png
mode = sprite
category = npc
fit = pad
anchor = bottom-center
target_width = 256
target_height = 256
dither = none
contrast = 1.00
saturation = 1.05
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 2048
kmeans_iters = 12
halo_strip = true
halo_luma_threshold = 220
note = NPC sprite pages  (cats / animals share the character-tier threshold so soft fur outlines stay intact)

[rule:cat_legacy_npcs]
match_category = zz_npcs_old
pattern = *.png
mode = sprite
category = npc
fit = pad
anchor = bottom-center
target_width = 256
target_height = 256
dither = none
contrast = 1.05
saturation = 1.10
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 2048
kmeans_iters = 16
halo_strip = false
halo_luma_threshold = 230
note = compact classic NPC animation frames

[rule:cat_sky_background]
match_category = zz_bg
pattern = 0.png
mode = screen
category = background
fit = contain
anchor = center
target_width = 256
target_height = 256
dither = ordered
contrast = 1.15
saturation = 1.20
sharpen_radius = 1.0
sharpen_percent = 100
sharpen_threshold = 2
kmeans_samples = 16384
kmeans_iters = 35
note = full-screen vertical shooter background

[rule:cat_foreground_layer]
match_category = zz_bg
pattern = 1.png
mode = sprite
category = background
fit = pad
anchor = top-left
target_width = 256
target_height = 256
dither = none
contrast = 1.05
saturation = 1.10
sharpen_radius = 0.0
sharpen_percent = 0
sharpen_threshold = 0
kmeans_samples = 4096
kmeans_iters = 20
halo_strip = false
halo_luma_threshold = 240
note = transparent near-field parallax layer

[rule:cat_screens]
match_category = screens
pattern = *.png
mode = screen
category = screens
# Drawn with the same vertical shrink as a backdrop.  These hold a figure
# against a plain field with a wide margin, so filling the screen and
# trimming the overhang costs only margin.
fit = crop
anchor = center
target_width = 256
target_height = 256
display_shrink_y = 175
dither = ordered
contrast = 1.20
saturation = 1.30
sharpen_radius = 1.5
sharpen_percent = 150
sharpen_threshold = 2
kmeans_samples = 16384
kmeans_iters = 35
note = full screen scenes

[rule:cat_titles]
match_category = titles
pattern = *.png
mode = screen
category = titles
# Title art runs to its own edges - a logo that fills the frame, a portrait
# poster - so there is no margin to spend and cropping would cut into the
# artwork.  Fitting the whole picture instead leaves the backdrop showing
# down either side, which is what a correctly proportioned picture on a
# wider screen is supposed to look like.
fit = contain
anchor = center
target_width = 256
target_height = 256
display_shrink_y = 175
dither = ordered
contrast = 1.15
saturation = 1.20
sharpen_radius = 1.0
sharpen_percent = 100
sharpen_threshold = 1
kmeans_samples = 16384
kmeans_iters = 35
note = title and logo screens

[rule:legacy_screens]
pattern = [0-9].png
mode = screen
category = background
fit = contain
anchor = center
target_width = 256
target_height = 256
dither = ordered
contrast = 1.20
saturation = 1.30
sharpen_radius = 1.5
sharpen_percent = 150
sharpen_threshold = 2
kmeans_samples = 8192
kmeans_iters = 25
note = legacy flat layout support
"""


def main() -> int:
    data_dir = Path(os.environ.get("ARTBOX_DATA_DIR", Path(__file__).resolve().parent)).resolve()
    data_dir.mkdir(parents=True, exist_ok=True)
    out_path = data_dir / "assets.cfg"
    out_path.write_text(CFG_TEXT, encoding="utf-8")
    print(f"Generated {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
