#!/usr/bin/env python3
"""
gen_eyecatcher.py — Generate eyecatcher.c from the assets manifest.

Reads assets_manifest.json, finds all entries with category=="eyecatcher",
and writes eyecatcher.c containing showEyeCatcherMVS() — an animation
function that sequences through the frames.  The function is compiled into
the game via the main Makefile.

Each frame is displayed for FRAME_DELAY seconds through showScreenN().
The generated call uses slot 1; slot 0 is reserved by the runtime.
"""

import argparse
import json
import os
import pathlib

DATA_DIR = os.environ.get("ARTBOX_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))
MANIFEST  = os.path.join(DATA_DIR, "assets_manifest.json")
_DEFAULT_OUT_C = pathlib.Path(__file__).resolve().parents[1] / "eyecatcher.c"

# Eyecatcher pacing:
# - short lead hold
# - one fast animation pass
# - one confirm pass
# - short final hold
LEAD_HOLD_MS = 80
ANIM_FRAME_MS = 50
FLASH_FRAME_MS = 35
FINAL_HOLD_MS = 100

# 256px wide generated art centered in the 320x224 display.
EC_X0 = 32
EC_Y0 = 24
EC_XR = 0xF
EC_YR = 0xFF
EC_MIN_CRT = 11

# Filenames that should use a shorter transition delay.
FLASH_FRAMES = {"4.png"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=None, help="Output path for eyecatcher.c")
    args = parser.parse_args()
    OUT_C = pathlib.Path(args.out) if args.out else _DEFAULT_OUT_C

    if not os.path.exists(MANIFEST):
        print("gen_eyecatcher: no manifest found, skipping.")
        return

    with open(MANIFEST, encoding="utf-8") as fh:
        specs = json.load(fh)

    frames = [s for s in specs if s.get("category", "").lower() == "eyecatcher"]
    if not frames:
        print("gen_eyecatcher: no eyecatcher entries in manifest, skipping.")
        return

    frames.sort(key=lambda s: (s["subdir"], s["name"]))

    lines = [
        "/*",
        " * eyecatcher.c — auto-generated by gen_eyecatcher.py",
        " * Do not edit by hand — regenerated each artbox build.",
        " */",
        "",
        '#include "sdk/macro.h"',
        '#include "sdk/neogeo.h"',
        '#include <stdint.h>',
        "",
        "#ifdef __cplusplus",
        "/* A USE_2D_PLUS build compiles this file as C++.  The showScreenN",
        " * bodies it calls live in main.c and keep C linkage, so these",
        " * declarations must too. */",
        'extern "C" {',
        "#endif",
        "",
        "#define EC_SPRITE_BASE 0x0040u",
        "",
        "#pragma GCC push_options",
        "#pragma GCC optimize (\"O0\")",
        "",
    ]

    # Forward-declare each showScreenN referenced by the frames
    for spec in frames:
        sid = spec["screen_id"]
        lines.append(
            f"void NEOGEO_USER showScreen{sid}"
            "(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);"
        )

    lines += [
        "",
        "void NEOGEO_USER showEyeCatcherMVS(void) {",
    ]

    lines += [
        "    clearFix();",
        "    clearSprs();",
        "",
    ]

    first = frames[0]
    lines += [
        f"    showScreen{first['screen_id']}({EC_X0}, {EC_Y0}, {hex(EC_XR)}, {hex(EC_YR)}, {EC_MIN_CRT}, 0x0000, EC_SPRITE_BASE);",
        f"    cyclexms({LEAD_HOLD_MS});",
        "",
    ]

    for _ in range(2):
        for spec in frames:
            sid = spec["screen_id"]
            delay = FLASH_FRAME_MS if spec["name"] in FLASH_FRAMES else ANIM_FRAME_MS
            lines += [
                f"    showScreen{sid}({EC_X0}, {EC_Y0}, {hex(EC_XR)}, {hex(EC_YR)}, {EC_MIN_CRT}, 0x0000, EC_SPRITE_BASE);",
                f"    cyclexms({delay});",
            ]
        lines.append("")

    last = frames[-1]
    lines += [
        f"    showScreen{last['screen_id']}({EC_X0}, {EC_Y0}, {hex(EC_XR)}, {hex(EC_YR)}, {EC_MIN_CRT}, 0x0000, EC_SPRITE_BASE);",
        f"    cyclexms({FINAL_HOLD_MS});",
        "",
    ]

    lines += [
        "    clearFix();",
        "    clearSprs();",
        "}",
        "",
        "#pragma GCC pop_options",
        "",
        "#ifdef __cplusplus",
        '}  /* extern "C" */',
        "#endif",
        "",
    ]

    OUT_C.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_eyecatcher: wrote {OUT_C}  ({len(frames)} frames)")


if __name__ == "__main__":
    main()
