#!/usr/bin/env python3
"""
gen_eyecatcher.py — Generate eyecatcher.c from the assets manifest.

Reads assets_manifest.json, finds all entries with category=="eyecatcher",
and writes eyecatcher.c containing showEyeCatcherMVS() — an animation
function that sequences through the frames.  The function is compiled into
the game via the main Makefile.

Each frame is displayed for FRAME_DELAY seconds, using the same sprite-
display convention as showScreenN() in screens.c (x=16, y=24, full-screen
16-strip layout).
"""

import json
import os
import pathlib

MANIFEST  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets_manifest.json")
OUT_C     = pathlib.Path(__file__).resolve().parents[1] / "eyecatcher.c"

# Logo frames hold for ~1.5 s — long enough to read, matches real NeoGeo pacing.
# The single flash/transition frame (4.png) gets a short burst.
LOGO_DELAY_MS  = 1500
FLASH_DELAY_MS = 250

# Filenames that are flash/transition frames (held briefly).
FLASH_FRAMES = {"4.png"}


def main():
    if not os.path.exists(MANIFEST):
        print("gen_eyecatcher: no manifest found, skipping.")
        return

    with open(MANIFEST, encoding="utf-8") as fh:
        specs = json.load(fh)

    frames = [s for s in specs if s.get("category", "").lower() == "eyecatcher"]
    if not frames:
        print("gen_eyecatcher: no eyecatcher entries in manifest, skipping.")
        return

    frames.sort(key=lambda s: (s["subdir"], s["name"]))

    lines = [
        "/*",
        " * eyecatcher.c — auto-generated by gen_eyecatcher.py",
        " * Do not edit by hand — regenerated each artbox build.",
        " */",
        "",
        '#include "sdk/macro.h"',
        '#include "sdk/neogeo.h"',
        '#include <stdint.h>',
        "",
        "#pragma GCC push_options",
        "#pragma GCC optimize (\"O0\")",
        "",
    ]

    # Forward-declare each showScreenN referenced by the frames
    for spec in frames:
        sid = spec["screen_id"]
        lines.append(
            f"void NEOGEO_USER showScreen{sid}"
            "(int x0,int y0,int xr,int yr,int min_crt_sz,uint16_t backdrop,uint16_t sprite_base);"
        )

    lines += [
        "",
        "void NEOGEO_USER showEyeCatcherMVS(void) {",
    ]

    for spec in frames:
        sid   = spec["screen_id"]
        delay = FLASH_DELAY_MS if spec["name"] in FLASH_FRAMES else LOGO_DELAY_MS
        lines += [
            f"    clearFix();",
            f"    clearSprs();",
            f"    showScreen{sid}(16, 24, 0xF, 0xAF, 16, 0x0000, 0);",
            f"    cyclexms({delay});",
            "",
        ]

    lines += [
        "    clearFix();",
        "    clearSprs();",
        "}",
        "",
        "#pragma GCC pop_options",
        "",
    ]

    OUT_C.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_eyecatcher: wrote {OUT_C}  ({len(frames)} frames)")


if __name__ == "__main__":
    main()
