@echo off
REM Usage: makeartbox.bat [GAME]
REM GAME defaults to "demo". GAME_ID is read from env (set by Makefile).
setlocal

set GAME=%~1
if "%GAME%"=="" set GAME=demo
if "%GAME_ID%"=="" set GAME_ID=777

set SCRIPT_DIR=%~dp0
set REPO_DIR=%SCRIPT_DIR%..
set GAME_ARTBOX_IN=%REPO_DIR%games\%GAME%\artbox\in
set GAME_ARTBOX_INFIX=%REPO_DIR%games\%GAME%\artbox\infix
set GAME_MAIN_C=%REPO_DIR%games\%GAME%\main.c
set GAME_EYECATCHER_C=%REPO_DIR%games\%GAME%\eyecatcher.c

cd /d "%SCRIPT_DIR%"

REM Remove stale junctions if present
if exist in  rmdir in
if exist infix rmdir infix

REM Create directory junctions so the pipeline scripts find in\ and infix\
mklink /J in    "%GAME_ARTBOX_IN%"
if errorlevel 1 goto :fail
mklink /J infix "%GAME_ARTBOX_INFIX%"
if errorlevel 1 goto :fail

py createromdb.py
if errorlevel 1 goto :cleanup_fail
py romdbimgimport.py
if errorlevel 1 goto :cleanup_fail
py gen_sprite_meta.py
if errorlevel 1 goto :cleanup_fail
rem py romdbfiximport.py
rem py fixtiles.py
py romtiles.py
if errorlevel 1 goto :cleanup_fail
for /f %%i in ('py count_assets.py') do set IMG_COUNT=%%i
echo Art pipeline [%GAME%]: %IMG_COUNT% images

if "%IMG_COUNT%"=="0" goto :skip_screens
py genmapfile.py %IMG_COUNT%
if errorlevel 1 goto :cleanup_fail
py genmapdb.py
if errorlevel 1 goto :cleanup_fail
py genscreens.py %IMG_COUNT% 16 16 16
if errorlevel 1 goto :cleanup_fail
py sync_main_screens.py --main-c "%GAME_MAIN_C%"
if errorlevel 1 goto :cleanup_fail
py gen_eyecatcher.py --out "%GAME_EYECATCHER_C%"
if errorlevel 1 goto :cleanup_fail
goto :after_screens

:skip_screens
echo Art pipeline [%GAME%]: no sprite images, skipping map/screen generation
(
  echo /*
  echo  * eyecatcher.c - stub ^(no eyecatcher art for this game^)
  echo  * Auto-generated by makeartbox.bat
  echo  */
  echo #include "sdk/macro.h"
  echo void showEyeCatcherMVS^(void^) {}
) > "%GAME_EYECATCHER_C%"

:after_screens
rem call romfx.bat
call romts.bat
if errorlevel 1 goto :cleanup_fail

REM Remove junctions (rmdir removes the junction, not the target)
rmdir in
rmdir infix

cd /d "%REPO_DIR%"
endlocal
goto :eof

:cleanup_fail
rmdir in  2>nul
rmdir infix 2>nul
cd /d "%REPO_DIR%"
endlocal
exit /b 1

:fail
cd /d "%REPO_DIR%"
endlocal
exit /b 1
