# Usage: GAME_ID=777 ./artbox/makeartbox.sh [GAME]
# GAME defaults to "demo". GAME_ID is read from env (set by Makefile).
GAME=${1:-demo}
: "${GAME_ID:=777}"
export GAME GAME_ID

# Resolve absolute paths before any cd so symlinks land correctly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

GAME_ARTBOX_IN="$REPO_DIR/games/$GAME/artbox/in"
GAME_ARTBOX_INFIX="$REPO_DIR/games/$GAME/artbox/infix"
GAME_ARTBOX_DIR="$REPO_DIR/games/$GAME/artbox"
GAME_MAIN_C="$REPO_DIR/games/$GAME/main.c"
GAME_EYECATCHER_C="$REPO_DIR/games/$GAME/eyecatcher.c"

mkdir -p "$GAME_ARTBOX_DIR"
cd "$GAME_ARTBOX_DIR"

PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_assets_cfg.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/createromdb.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/romdbimgimport.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_sprite_meta.py"
#python3 romdbfiximport.py
#python3 fixtiles.py
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/romtiles.py"
IMG_COUNT=$(PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/count_assets.py")
echo "Art pipeline [$GAME]: $IMG_COUNT images"

if [ "${IMG_COUNT:-0}" -gt 0 ] 2>/dev/null; then
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genmapfile.py" $IMG_COUNT
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genmapdb.py"
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genscreens.py" $IMG_COUNT 16 16 16
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/sync_main_screens.py" --main-c "$GAME_MAIN_C"
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_eyecatcher.py" --out "$GAME_EYECATCHER_C"
else
    echo "Art pipeline [$GAME]: no sprite images, skipping map/screen generation"
    # Write a stub so the game links without art assets
    cat > "$GAME_EYECATCHER_C" << 'EYECATCHER_EOF'
/*
 * eyecatcher.c — stub (no eyecatcher art for this game)
 * Auto-generated by makeartbox.sh
 */
#include "sdk/macro.h"
void showEyeCatcherMVS(void) {}
EYECATCHER_EOF
fi
#./romfx.sh
GAME="$GAME" GAME_ID="$GAME_ID" "$SCRIPT_DIR/romts.sh"

cd "$REPO_DIR"
