# Usage: GAME_ID=777 ./artbox/makeartbox.sh [GAME]
# GAME defaults to "demo". GAME_ID is read from env (set by Makefile).
GAME=${1:-demo}
: "${GAME_ID:=777}"
export GAME GAME_ID

# Resolve absolute paths before any cd so symlinks land correctly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# GAME_ART_FROM names another game whose source artwork this game draws on.
# Only the inputs are shared: the tables, palettes and C/S ROMs below are all
# still generated into this game's own artbox under its own GAME_ID.
ART_SRC_GAME="${GAME_ART_FROM:-$GAME}"
GAME_ARTBOX_IN="$REPO_DIR/games/$ART_SRC_GAME/artbox/in"
GAME_ARTBOX_INFIX="$REPO_DIR/games/$ART_SRC_GAME/artbox/infix"
export ARTBOX_IN_DIR="$GAME_ARTBOX_IN"
export ARTBOX_INFIX_DIR="$GAME_ARTBOX_INFIX"
if [ "$ART_SRC_GAME" != "$GAME" ]; then
    echo "Art pipeline [$GAME]: source art from games/$ART_SRC_GAME/artbox"
fi
GAME_ARTBOX_DIR="$REPO_DIR/games/$GAME/artbox"
GAME_MAIN_C="$REPO_DIR/games/$GAME/main.c"
GAME_EYECATCHER_C="$REPO_DIR/games/$GAME/eyecatcher.c"

mkdir -p "$GAME_ARTBOX_DIR"
# The importers list these directories rather than probing for them, so a game
# that has not been given any art yet must still find them there and empty.
mkdir -p "$GAME_ARTBOX_IN" "$GAME_ARTBOX_INFIX"
cd "$GAME_ARTBOX_DIR"

PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_assets_cfg.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/createromdb.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/romdbimgimport.py"
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_sprite_meta.py"
#python3 romdbfiximport.py
#python3 fixtiles.py
PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/romtiles.py"
IMG_COUNT=$(PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/count_assets.py")
echo "Art pipeline [$GAME]: $IMG_COUNT images"

if [ "${IMG_COUNT:-0}" -gt 0 ] 2>/dev/null; then
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genmapfile.py" $IMG_COUNT
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genmapdb.py"
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/genscreens.py" $IMG_COUNT 16 16 16
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/sync_main_screens.py" --main-c "$GAME_MAIN_C"
    PYTHONDONTWRITEBYTECODE=1 ARTBOX_DATA_DIR="$GAME_ARTBOX_DIR" python3 "$SCRIPT_DIR/gen_eyecatcher.py" --out "$GAME_EYECATCHER_C"
else
    echo "Art pipeline [$GAME]: no sprite images, skipping map/screen generation"
    # Write a stub so the game links without art assets
    cat > "$GAME_EYECATCHER_C" << 'EYECATCHER_EOF'
/*
 * eyecatcher.c — stub (no eyecatcher art for this game)
 * Auto-generated by makeartbox.sh
 */
#include "sdk/macro.h"
/* NEOGEO_USER places this in the section the ROM link keeps; without it the
 * stub lands in .text, which is stripped, and user.c fails to resolve it. */
void NEOGEO_USER showEyeCatcherMVS(void) {}
EYECATCHER_EOF
fi
#./romfx.sh
GAME="$GAME" GAME_ID="$GAME_ID" "$SCRIPT_DIR/romts.sh"

cd "$REPO_DIR"
