# Usage: GAME_ID=777 ./artbox/makeartbox.sh [GAME]
# GAME defaults to "demo". GAME_ID is read from env (set by Makefile).
GAME=${1:-demo}
: "${GAME_ID:=777}"
export GAME_ID

# Resolve absolute paths before any cd so symlinks land correctly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

GAME_ARTBOX_IN="$REPO_DIR/games/$GAME/artbox/in"
GAME_ARTBOX_INFIX="$REPO_DIR/games/$GAME/artbox/infix"
GAME_MAIN_C="$REPO_DIR/games/$GAME/main.c"
GAME_EYECATCHER_C="$REPO_DIR/games/$GAME/eyecatcher.c"

cd "$SCRIPT_DIR"

# Remove stale symlinks and create fresh ones pointing to per-game asset dirs
rm -f in infix
ln -sfn "$GAME_ARTBOX_IN"    in
ln -sfn "$GAME_ARTBOX_INFIX" infix

python3 createromdb.py
python3 romdbimgimport.py
python3 gen_sprite_meta.py
#python3 romdbfiximport.py
#python3 fixtiles.py
python3 romtiles.py
IMG_COUNT=$(python3 count_assets.py)
echo "Art pipeline [$GAME]: $IMG_COUNT images"

if [ "${IMG_COUNT:-0}" -gt 0 ] 2>/dev/null; then
    python3 genmapfile.py $IMG_COUNT
    python3 genmapdb.py
    python3 genscreens.py $IMG_COUNT 16 16 16
    python3 sync_main_screens.py --main-c "$GAME_MAIN_C"
    python3 gen_eyecatcher.py --out "$GAME_EYECATCHER_C"
else
    echo "Art pipeline [$GAME]: no sprite images, skipping map/screen generation"
    # Write a stub so the game links without art assets
    cat > "$GAME_EYECATCHER_C" << 'EYECATCHER_EOF'
/*
 * eyecatcher.c — stub (no eyecatcher art for this game)
 * Auto-generated by makeartbox.sh
 */
#include "sdk/macro.h"
void showEyeCatcherMVS(void) {}
EYECATCHER_EOF
fi
#./romfx.sh
./romts.sh

# Remove temporary symlinks
rm -f in infix

cd "$REPO_DIR"
