@echo off
REM Usage: makeartbox.bat [GAME]
REM GAME defaults to "demo". GAME_ID is read from env (set by Makefile).
setlocal

set GAME=%~1
if "%GAME%"=="" set GAME=demo
if "%GAME_ID%"=="" set GAME_ID=777

REM Resolve absolute repo root — %~dp0 includes trailing \, so ".." alone would give "artbox\.."
for %%i in ("%~dp0..") do set REPO_DIR=%%~fi

set GAME_ARTBOX_IN=%REPO_DIR%\games\%GAME%\artbox\in
set GAME_ARTBOX_INFIX=%REPO_DIR%\games\%GAME%\artbox\infix
set GAME_ARTBOX_DIR=%REPO_DIR%\games\%GAME%\artbox
set GAME_MAIN_C=%REPO_DIR%\games\%GAME%\main.c
set GAME_EYECATCHER_C=%REPO_DIR%\games\%GAME%\eyecatcher.c

if not exist "%GAME_ARTBOX_DIR%" mkdir "%GAME_ARTBOX_DIR%"
cd /d "%GAME_ARTBOX_DIR%"

set ARTBOX_DATA_DIR=%GAME_ARTBOX_DIR%
set PYTHONDONTWRITEBYTECODE=1
py "%~dp0gen_assets_cfg.py"
if errorlevel 1 goto :cleanup_fail
py "%~dp0createromdb.py"
if errorlevel 1 goto :cleanup_fail
py "%~dp0romdbimgimport.py"
if errorlevel 1 goto :cleanup_fail
py "%~dp0gen_sprite_meta.py"
if errorlevel 1 goto :cleanup_fail
rem py romdbfiximport.py
rem py fixtiles.py
py "%~dp0romtiles.py"
if errorlevel 1 goto :cleanup_fail
if not exist "%GAME_ARTBOX_DIR%\1c.c1" (
  echo ERROR: missing C1 intermediate at games\%GAME%\artbox\1c.c1
  goto :cleanup_fail
)
if not exist "%GAME_ARTBOX_DIR%\2c.c2" (
  echo ERROR: missing C2 intermediate at games\%GAME%\artbox\2c.c2
  goto :cleanup_fail
)
for /f %%i in ('py "%~dp0count_assets.py"') do set IMG_COUNT=%%i
echo Art pipeline [%GAME%]: %IMG_COUNT% images

if "%IMG_COUNT%"=="0" goto :skip_screens
py "%~dp0genmapfile.py" %IMG_COUNT%
if errorlevel 1 goto :cleanup_fail
py "%~dp0genmapdb.py"
if errorlevel 1 goto :cleanup_fail
py "%~dp0genscreens.py" %IMG_COUNT% 16 16 16
if errorlevel 1 goto :cleanup_fail
py "%~dp0sync_main_screens.py" --main-c "%GAME_MAIN_C%"
if errorlevel 1 goto :cleanup_fail
py "%~dp0gen_eyecatcher.py" --out "%GAME_EYECATCHER_C%"
if errorlevel 1 goto :cleanup_fail
goto :after_screens

:skip_screens
echo Art pipeline [%GAME%]: no sprite images, skipping map/screen generation
(
  echo /*
  echo  * eyecatcher.c - stub ^(no eyecatcher art for this game^)
  echo  * Auto-generated by makeartbox.bat
  echo  */
  echo #include "sdk/macro.h"
  echo void showEyeCatcherMVS^(void^) {}
) > "%GAME_EYECATCHER_C%"

:after_screens
rem call romfx.bat
call "%~dp0romts.bat"
if errorlevel 1 goto :cleanup_fail

cd /d "%REPO_DIR%"
endlocal
goto :eof

:cleanup_fail
cd /d "%REPO_DIR%"
endlocal
exit /b 1
