#ifndef SOUND_VOICE_IDS_H
#define SOUND_VOICE_IDS_H

/* Generated by sound/tools/vrom.py from samples/out_a_voice. */
#define SOUND_VOICE_BANK_BASE  SOUND_SFX_COUNT
#define SOUND_VOICE_COUNT      0
#define SOUND_VOICE_BANK_END   (SOUND_VOICE_BANK_BASE + SOUND_VOICE_COUNT)
#define SOUND_VOICE_LETTER_BASE SOUND_VOICE_BANK_BASE


#define SOUND_VOICE_LETTER_COUNT 0

#endif
