#ifndef SOUND_VOICE_IDS_H
#define SOUND_VOICE_IDS_H

/* Generated by sound/tools/vrom.py from samples/out_a_voice. */
#define SOUND_VOICE_BANK_BASE  SOUND_SFX_COUNT
#define SOUND_VOICE_COUNT      22
#define SOUND_VOICE_BANK_END   (SOUND_VOICE_BANK_BASE + SOUND_VOICE_COUNT)
#define SOUND_VOICE_LETTER_BASE SOUND_VOICE_BANK_BASE

#define SOUND_VOICE_V01_RISE                   (SOUND_VOICE_BANK_BASE +  0)  /* v01_rise.adpcma */
#define SOUND_VOICE_V02_SURGE                  (SOUND_VOICE_BANK_BASE +  1)  /* v02_surge.adpcma */
#define SOUND_VOICE_V03_ART                    (SOUND_VOICE_BANK_BASE +  2)  /* v03_art.adpcma */
#define SOUND_VOICE_V04_LEAP                   (SOUND_VOICE_BANK_BASE +  3)  /* v04_leap.adpcma */
#define SOUND_VOICE_V05_LILY                   (SOUND_VOICE_BANK_BASE +  4)  /* v05_lily.adpcma */
#define SOUND_VOICE_V06_FREE                   (SOUND_VOICE_BANK_BASE +  5)  /* v06_free.adpcma */
#define SOUND_VOICE_V07_START                  (SOUND_VOICE_BANK_BASE +  6)  /* v07_start.adpcma */
#define SOUND_VOICE_V08_RETRY                  (SOUND_VOICE_BANK_BASE +  7)  /* v08_retry.adpcma */
#define SOUND_VOICE_V09_WIN                    (SOUND_VOICE_BANK_BASE +  8)  /* v09_win.adpcma */
#define SOUND_VOICE_V10_ELDER                  (SOUND_VOICE_BANK_BASE +  9)  /* v10_elder.adpcma */
#define SOUND_VOICE_V11_MAIDEN                 (SOUND_VOICE_BANK_BASE + 10)  /* v11_maiden.adpcma */
#define SOUND_VOICE_V12_SPIRIT                 (SOUND_VOICE_BANK_BASE + 11)  /* v12_spirit.adpcma */
#define SOUND_VOICE_V13_SUNBOY                 (SOUND_VOICE_BANK_BASE + 12)  /* v13_sunboy.adpcma */
#define SOUND_VOICE_V14_LUNA_RISE              (SOUND_VOICE_BANK_BASE + 13)  /* v14_luna_rise.adpcma */
#define SOUND_VOICE_V15_LUNA_SURGE             (SOUND_VOICE_BANK_BASE + 14)  /* v15_luna_surge.adpcma */
#define SOUND_VOICE_V16_LUNA_ART               (SOUND_VOICE_BANK_BASE + 15)  /* v16_luna_art.adpcma */
#define SOUND_VOICE_V17_LUNA_LEAP              (SOUND_VOICE_BANK_BASE + 16)  /* v17_luna_leap.adpcma */
#define SOUND_VOICE_V18_LUNA_LILY              (SOUND_VOICE_BANK_BASE + 17)  /* v18_luna_lily.adpcma */
#define SOUND_VOICE_V19_LUNA_FREE              (SOUND_VOICE_BANK_BASE + 18)  /* v19_luna_free.adpcma */
#define SOUND_VOICE_V20_LUNA_START             (SOUND_VOICE_BANK_BASE + 19)  /* v20_luna_start.adpcma */
#define SOUND_VOICE_V21_LUNA_RETRY             (SOUND_VOICE_BANK_BASE + 20)  /* v21_luna_retry.adpcma */
#define SOUND_VOICE_V22_LUNA_WIN               (SOUND_VOICE_BANK_BASE + 21)  /* v22_luna_win.adpcma */

#define SOUND_VOICE_LETTER_COUNT 0

#endif
