#ifndef SOUND_IDS_H
#define SOUND_IDS_H

enum {
	SOUND_MUSIC_ENDING_CREDITS       = 0,
	SOUND_MUSIC_SAMURAI_GAME_LOOP    = 1,
	SOUND_MUSIC_SAMURAI_ENDING_SCENE = 2,
	SOUND_MUSIC_SHOP_JINGLE          = 3,
	SOUND_MUSIC_SAMURAI_BATTLE_LOOP  = 4,
	SOUND_MUSIC_EAGLE_FANFARE        = 5,
	SOUND_MUSIC_WARRIOR_BATTLE       = 6,
	SOUND_MUSIC_BOSS_TENSION         = 7
};

enum {
	SOUND_SFX_COIN_CHIME = 0,
	SOUND_SFX_START_SLASH = 1,
	SOUND_SFX_TITLE_GONG = 2,
	SOUND_SFX_INTRO_TAIKO = 3,
	SOUND_SFX_FOOTSTEP = 4,
	SOUND_SFX_SHORT_SHOUT = 5,
	SOUND_SFX_BLADE_WHOOSH = 6,
	SOUND_SFX_IMPACT_HIT = 7,
	SOUND_SFX_STRING_PHRASE = 8,
	SOUND_SFX_LOW_DRUM = 9,
	SOUND_SFX_READY_VOICE = 10,
	SOUND_SFX_ATTACK_VOICE = 11
};

enum {
	SOUND_BED_TITLE_THEME = 0,
	SOUND_BED_STAGE_ONE = 1,
	SOUND_BED_STAGE_TWO = 2,
	SOUND_BED_ENDING_THEME = 3,
	SOUND_BED_EYECATCHER = 4
};

enum {
	SOUND_FM_VICTORY_JINGLE = 0,
	SOUND_FM_DUEL_SUSPENSE  = 1,
	SOUND_FM_MENU_MAJOR     = 2,
	SOUND_FM_ATTRACT_FAST   = 3,
	SOUND_FM_PATCH_SHOWCASE = 4,
	SOUND_FM_BASS_MOTIF     = 5,
	SOUND_FM_GAMEOVER_DARK  = 6,
	SOUND_FM_SAMURAI_MINOR  = 7
};

enum {
	SOUND_SSG_BATTLE_STING  = 0,
	SOUND_SSG_MENU_LOOP     = 1,
	SOUND_SSG_INSERT_COIN   = 2,
	SOUND_SSG_ARCADE_ALERT  = 3
};

enum {
	SOUND_VOICE_GET_READY = 1,
	SOUND_VOICE_ATTACK = 2
};

#endif
