#!/usr/bin/env python3
"""Generate sdk/2d_engine/ng_trig_table.c: the tables behind ng_trig.

    python3 tools/gen_trig.py --out sdk/2d_engine/ng_trig_table.c   (rewrite it if it changed)
    python3 tools/gen_trig.py --check sdk/2d_engine/ng_trig_table.c (fail if it differs)
    python3 tools/gen_trig.py                                       (print it)

Tables:
    ng_trig_sin_tab[256]   sin(2 pi a / 256) in 1.14 fixed point (1.0 = 16384)
    ng_trig_atan_tab[8]    atan(2^-i) in 1/256ths of an angle step, for the
                           CORDIC in ng_atan2()

Every value is worked out in decimal arithmetic to 50 digits (Python's
decimal module), not with the host's floating-point sine, and the file is
written with LF line ends: the bytes are the same on every host.
"""

import argparse
import sys
from decimal import Decimal, ROUND_HALF_EVEN, getcontext
from pathlib import Path

getcontext().prec = 50

STEPS = 256            # one full turn
ONE = 16384            # 1.0 in 1.14
ATAN_ITERATIONS = 8


def arctan_inv(n):
    """atan(1/n) by its series, n > 1."""
    x = Decimal(1) / n
    x2 = x * x
    term, total, k = x, Decimal(0), 0
    while term:
        total += term / (2 * k + 1) if k % 2 == 0 else -term / (2 * k + 1)
        term *= x2
        k += 1
        if abs(term) < Decimal(10) ** -60:
            break
    return total


def arctan(x):
    """atan(x) for 0 <= x <= 1: the series, after halving the angle twice."""
    for _ in range(2):   # atan(x) = 2 atan(x / (1 + sqrt(1 + x^2)))
        x = x / (1 + (1 + x * x).sqrt())
    x2 = x * x
    term, total, k = x, Decimal(0), 0
    while abs(term) > Decimal(10) ** -60:
        total += term / (2 * k + 1) if k % 2 == 0 else -term / (2 * k + 1)
        term *= x2
        k += 1
    return total * 4


PI = 16 * arctan_inv(5) - 4 * arctan_inv(239)


def sin(x):
    x2 = x * x
    term, total, k = x, Decimal(0), 1
    while abs(term) > Decimal(10) ** -60:
        total += term
        term = -term * x2 / ((2 * k) * (2 * k + 1))
        k += 1
    return total


def rounded(value):
    return int(value.quantize(Decimal(1), rounding=ROUND_HALF_EVEN))


def tables():
    sin_tab = []
    for a in range(STEPS):
        # Fold into the first quarter so the series always converges fast.
        q, r = divmod(a, STEPS // 4)
        k = r if q % 2 == 0 else STEPS // 4 - r
        v = rounded(sin(PI * 2 * k / STEPS) * ONE)
        sin_tab.append(v if q < 2 else -v)
    step = PI * 2 / STEPS
    atan_tab = [rounded(arctan(Decimal(1) / (2 ** i)) / step * 256) for i in range(ATAN_ITERATIONS)]
    return sin_tab, atan_tab


def render():
    sin_tab, atan_tab = tables()
    lines = [
        "/*",
        " * ng_trig_table.c -- the tables behind ng_trig (see ng_trig.h)",
        " *",
        " * GENERATED by tools/gen_trig.py -- do not edit by hand. Every game build",
        " * regenerates it and \"make unit-tests\" checks it; the bytes are the same",
        " * on every host.",
        " */",
        "",
        '#include "ng_trig.h"',
        "",
        "/* sin(2 pi a / 256) in 1.14 fixed point: 16384 is 1.0. */",
        "const int16_t ng_trig_sin_tab[256] = {",
    ]
    for row in range(0, STEPS, 8):
        lines.append("    " + " ".join(f"{v:6d}," for v in sin_tab[row:row + 8]))
    lines += [
        "};",
        "",
        f"/* atan(2^-i), i = 0..{ATAN_ITERATIONS - 1}, in 1/256ths of an angle step. */",
        f"const uint16_t ng_trig_atan_tab[{ATAN_ITERATIONS}] = {{",
        "    " + " ".join(f"{v}u," for v in atan_tab),
        "};",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--out", type=Path, help="write the table file (only if it changed)")
    group.add_argument("--check", type=Path, help="fail if the table file differs from a fresh one")
    args = ap.parse_args()
    text = render().encode("ascii")
    if args.check:
        if not args.check.is_file() or args.check.read_bytes() != text:
            print(f"gen_trig: {args.check} is not what tools/gen_trig.py generates; "
                  f"run: python3 tools/gen_trig.py --out {args.check}", file=sys.stderr)
            return 1
        print(f"gen_trig: {args.check} is up to date")
        return 0
    if args.out:
        if not args.out.is_file() or args.out.read_bytes() != text:
            args.out.write_bytes(text)
            print(f"gen_trig: wrote {args.out}")
        return 0
    sys.stdout.write(text.decode("ascii"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
